### ISSUE TITLE
Wrong property name for client secret

### ISSUE THREAD

**Issue by shtas** [selaias/strava#1]
Hi!
[configureLoginServiceDialogForStrava.fields()](https://github.com/selaias/strava/blob/master/strava_configure.js#L9) sets a property called `client_secret`, but [getTokenResponse()](https://github.com/selaias/strava/blob/master/strava_server.js#L48) reads from a prop named `secret`

This causes the login to fail if you use strava_configure to configure the service.

The readme in [selaias/accounts-strava](https://github.com/selaias/accounts-strava/blob/master/README.md) sets the `secret` property, so if you configure that way, the login works.

I can make a pull request, if so, do you want me to change
- `strava_server.js` or
- `strava_configure.js` and the readme of selaias/accounts-strava?

**Comment by selaias** [comment]
Hi, 
You are right, I missed that since I have set the properties manually. 
Please go ahead with a pull request, I would prefer to keep it consistent and change the configuration to 'secret'.

Thanks for spotting. 

Probably this exists elsewhere, I'm gonna check them all now. Thanks
