### ISSUE TITLE
Why approval_prompt=force in the loginUrl

### ISSUE THREAD

**Issue by shtas** [selaias/strava#3]
First of all:
thank you very much for making your Strava OAuth and accounts Meteor packages available :smile:

I've got a question regarding the [loginUrl](https://github.com/selaias/strava/blob/master/strava_client.js#L30) though: what is the reason you set `approval_prompt` to `force`? This means users have to approve your Strava App every time they sign in.

**Comment by selaias** [comment]
Hey :)
I remember there was a reason for setting `force` to `approval_prompt` but cannot recall the actual reason. 
I believe it has to do with mobile devices and/or caching. I'm going to try to find the source.

S

**Comment by selaias** [comment]
I'm sorry I forgot about this. Changed to default (auto)
